// Function to create and display a QR code image
function createQrImage(qrCodeDataUrl, containerId) {
  // 1. Get a reference to the container element where the image will be placed
  const container = document.getElementById(containerId);

  // Optional: Clear any existing content in the container before adding a new QR code
  if (container) {
    container.innerHTML = '';
  }

  // 2. Create a new <img> element
  const qrImageElement = document.createElement('img');

  // 3. Set the src attribute to the QR code data URL
  qrImageElement.src = qrCodeDataUrl;

  // Optional: Set other attributes like alt text, width, height, or classes for styling
  qrImageElement.alt = 'QR Code';
  qrImageElement.width = 200; // Example width
  qrImageElement.height = 200; // Example height
  qrImageElement.classList.add('qr-code-image'); // Add a class for CSS styling

  // 4. Append the <img> element to the container
  if (container) {
    container.appendChild(qrImageElement);
  } else {
    console.error(`Container with ID "${containerId}" not found.`);
  }
}

// Example usage (assuming you have a qrCodeDataUrl from a library)
// In a real application, qrCodeDataUrl would be generated by a QR code library
const exampleQrCodeDataUrl = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADIAQMAAACQJHqGAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAFpJREFUKJFjYBgFo2AUjIJRMApGwSigSgYGBgYGJgZGdgZGhgZGxgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGAAB+VfIuO9Z96AAAAAElFTkSuQmCC'; // This is a placeholder, replace with actual QR code data

// Call the function to create and display the QR code image in an element with id "qrCodeContainer"
createQrImage(exampleQrCodeDataUrl, 'qrCodeContainer');// Function to create and display a QR code image
function createQrImage(qrCodeDataUrl, containerId) {
  // 1. Get a reference to the container element where the image will be placed
  const container = document.getElementById(containerId);

  // Optional: Clear any existing content in the container before adding a new QR code
  if (container) {
    container.innerHTML = '';
  }

  // 2. Create a new <img> element
  const qrImageElement = document.createElement('img');

  // 3. Set the src attribute to the QR code data URL
  qrImageElement.src = qrCodeDataUrl;

  // Optional: Set other attributes like alt text, width, height, or classes for styling
  qrImageElement.alt = 'QR Code';
  qrImageElement.width = 200; // Example width
  qrImageElement.height = 200; // Example height
  qrImageElement.classList.add('qr-code-image'); // Add a class for CSS styling

  // 4. Append the <img> element to the container
  if (container) {
    container.appendChild(qrImageElement);
  } else {
    console.error(`Container with ID "${containerId}" not found.`);
  }
}

// Example usage (assuming you have a qrCodeDataUrl from a library)
// In a real application, qrCodeDataUrl would be generated by a QR code library
const exampleQrCodeDataUrl = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADIAQMAAACQJHqGAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAFpJREFUKJFjYBgFo2AUjIJRMApGwSigSgYGBgYGJgZGdgZGhgZGxgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGhgZGAAB+VfIuO9Z96AAAAAElFTkSuQmCC'; // This is a placeholder, replace with actual QR code data

// Call the function to create and display the QR code image in an element with id "qrCodeContainer"
createQrImage(exampleQrCodeDataUrl, 'qrCodeContainer');



fs.readFile('./message.txt','utf8', (err, data) => {
  if (err) {
    console.error(err);
    return;
  }
  console.log(data);
});
